export enum EventType {
  // Request Events (from services)
  INVENTORY_ITEM_ADDED = 'INVENTORY_ITEM_ADDED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_ITEM_DELETED = 'INVENTORY_ITEM_DELETED',
  INVENTORY_STOCK_REDUCED = 'INVENTORY_STOCK_REDUCED',
  INVENTORY_STOCK_INCREASED = 'INVENTORY_STOCK_INCREASED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  CART_CLEAR_REQUESTED = 'CART_CLEAR_REQUESTED',

  // Result Events (from event processor to notification service)
  ITEM_CREATED_SUCCESS = 'ITEM_CREATED_SUCCESS',
  ITEM_CREATED_FAILED = 'ITEM_CREATED_FAILED',
  ITEM_UPDATED_SUCCESS = 'ITEM_UPDATED_SUCCESS',
  ITEM_UPDATED_FAILED = 'ITEM_UPDATED_FAILED',
  ITEM_DELETED_SUCCESS = 'ITEM_DELETED_SUCCESS',
  ITEM_DELETED_FAILED = 'ITEM_DELETED_FAILED',
  STOCK_REDUCED_SUCCESS = 'STOCK_REDUCED_SUCCESS',
  STOCK_REDUCED_FAILED = 'STOCK_REDUCED_FAILED',
  STOCK_INCREASED_SUCCESS = 'STOCK_INCREASED_SUCCESS',
  STOCK_INCREASED_FAILED = 'STOCK_INCREASED_FAILED',
  ORDER_CREATED_SUCCESS = 'ORDER_CREATED_SUCCESS',
  ORDER_CREATED_FAILED = 'ORDER_CREATED_FAILED',
}

export const KafkaTopics = {
  INVENTORY_EVENTS: 'inventory-events',
  ORDER_EVENTS: 'order-events',
  CART_EVENTS: 'cart-events',
  NOTIFICATION_EVENTS: 'notification-events', // New topic for result events
} as const;
