
import { Product, MockUser, Order, CartItem } from '../types';

export const db = {
    products: [
      {
        id: '1',
        name: 'Men\'s Running Shoes',
        description: 'Lightweight and comfortable running shoes for men, perfect for daily runs.',
        price: 120.00,
        image: 'https://picsum.photos/seed/running-shoes/800/800',
        category: 'Men',
        stock: 50,
        sizes: ['8', '9', '10', '11', '12'],
        colors: ['Red', 'Black', 'White'],
        isNewArrival: true,
      },
      {
        id: '2',
        name: 'Women\'s Yoga Pants',
        description: 'Stretchy and breathable yoga pants that offer maximum flexibility and comfort.',
        price: 75.00,
        image: 'https://picsum.photos/seed/yoga-pants/800/800',
        category: 'Women',
        stock: 75,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Purple', 'Gray', 'Black'],
        isNewArrival: true,
      },
      {
        id: '3',
        name: 'Unisex Sports Hoodie',
        description: 'A warm and stylish hoodie suitable for workouts or casual wear.',
        price: 90.00,
        image: 'https://picsum.photos/seed/hoodie/800/800',
        category: 'Accessories',
        stock: 60,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Gray', 'Navy', 'Black'],
        isNewArrival: false,
      },
      {
        id: '4',
        name: 'Kids\' Soccer Jersey',
        description: 'Official team jersey for young soccer fans. Breathable fabric.',
        price: 65.00,
        image: 'https://picsum.photos/seed/jersey/800/800',
        category: 'Kids',
        stock: 40,
        sizes: ['YS', 'YM', 'YL'],
        colors: ['Blue', 'White'],
        isNewArrival: false,
      },
      {
        id: '5',
        name: 'Performance Socks',
        description: 'Cushioned performance socks for all types of sports activities.',
        price: 15.00,
        image: 'https://picsum.photos/seed/socks/800/800',
        category: 'Accessories',
        stock: 120,
        sizes: ['One Size'],
        colors: ['White', 'Black'],
        isNewArrival: true,
      },
      {
        id: '6',
        name: 'Women\'s Sports Bra',
        description: 'High-support sports bra for intense workouts. Moisture-wicking fabric.',
        price: 50.00,
        image: 'https://picsum.photos/seed/sports-bra/800/800',
        category: 'Women',
        stock: 80,
        sizes: ['S', 'M', 'L'],
        colors: ['Pink', 'Black', 'Teal'],
        isNewArrival: false,
      },
       {
        id: '7',
        name: 'Men\'s Compression Shorts',
        description: 'Enhance your performance with these comfortable compression shorts.',
        price: 45.00,
        image: 'https://picsum.photos/seed/shorts/800/800',
        category: 'Men',
        stock: 3,
        sizes: ['M', 'L', 'XL'],
        colors: ['Black', 'Blue'],
        isNewArrival: true,
      },
      {
        id: '8',
        name: 'Kids\' Athletic Sneakers',
        description: 'Durable and stylish sneakers for active kids.',
        price: 55.00,
        image: 'https://picsum.photos/seed/kids-sneakers/800/800',
        category: 'Kids',
        stock: 65,
        sizes: ['3', '4', '5'],
        colors: ['Green', 'Orange'],
        isNewArrival: false,
      },
    ] as Product[],
    users: [
      {
        id: 'user-admin',
        name: 'Admin User',
        email: 'admin@playfit.com',
        password_DO_NOT_USE_IN_PRODUCTION: 'admin123',
        role: 'admin',
      },
      {
        id: 'user-1',
        name: 'John Doe',
        email: 'user@playfit.com',
        password_DO_NOT_USE_IN_PRODUCTION: 'user123',
        role: 'user',
      },
    ] as MockUser[],
    orders: [] as Order[],
    userCarts: {} as { [userId: string]: CartItem[] }
};
